# -*- coding: utf-8 -*-
"""ArbolDesicionClasificacion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Agavwrzy3bFs1ZQ4i-gtjdbjPQ9NCxRg

**ARBOL DE DECISION PARA CLASIFICACION - DATASET_IRIS**

---

Importamos el dataset de iris y árbol de decisión para clasificación
"""

from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier

"""Cargamos el dataset"""

iris = load_iris()

"""Informacion del dataset iris"""

print(iris.DESCR)

"""Mostramos las 6 filas donde ocurre un cambio de clase"""

print(iris.data[47:53,:])

"""Para la variable a predecir también hacemos lo mismo"""

print(iris.target[47:53])

"""Vamos a crear y entrenar un árbol de decisión para clasificar los datos de Iris

vamos a usar un árbol de profundidad 2
"""

tree = DecisionTreeClassifier(max_depth=2, random_state=42)

"""entrenamiento del árbol"""

tree.fit(iris.data, iris.target)

"""Usamos el método predict para obtener predicciones"""

print( tree.predict(iris.data[47:53]) )

"""Para saber las probabilidades podemos usar el método predict_proba"""

print( tree.predict_proba(iris.data[47:53]) )

"""La primera clase -> "Setosa" es la primera columna, la segunda clase en la segunda y asi sucesivamente"""