# -*- coding: utf-8 -*-
"""EJEMPLO# clasificación

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V_WRq3DRfY6x7prnUsN0ijt52ipMAZwG
"""

# importamos las librerías que necesitamos
from sklearn.datasets import load_iris # datos de iris
from sklearn.tree import DecisionTreeClassifier # árbol de decisión para clasificación

iris = load_iris()
print(iris.DESCR) # información sobre del conjunto de datos iris

# lo más relevante es:
#    :Number of Instances: 150 (50 in each of three classes)
#    :Number of Attributes: 4 numeric, predictive attributes and the class
#    :Attribute Information:
#        - sepal length in cm
#        - sepal width in cm
#        - petal length in cm
#        - petal width in cm
#        - class:
#                - Iris-Setosa
#                - Iris-Versicolour
#                - Iris-Virginica

print(iris.data[48:52,:])

print(iris.target[48:52])

tree = DecisionTreeClassifier(max_depth=2, random_state=42) # vamos a usar un árbol de profundidad 2
tree.fit(iris.data, iris.target) # entrenamiento del árbol
# podemos usar el método predict para obtener predicciones
print( tree.predict(iris.data[47:53]) )

print( tree.predict_proba(iris.data[47:53]) )